# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Use a Node.js image as the builder
FROM node:18-alpine AS builder

# Set the working directory
WORKDIR /app

# Copy package files
COPY package.json package-lock.json ./

# Install dependencies
RUN npm install --ignore-scripts

# Copy source files
COPY src/ ./src

# Copy TypeScript configuration
COPY tsconfig.json ./

# Build the project
RUN npm run build

# Use a smaller Node.js image for the final stage
FROM node:18-alpine AS runtime

# Set the working directory
WORKDIR /app

# Copy built files and necessary metadata from the builder stage
COPY --from=builder /app/build ./build
COPY --from=builder /app/package.json ./package.json
COPY --from=builder /app/package-lock.json ./package-lock.json
COPY --from=builder /app/node_modules ./node_modules

# Set environment variables if needed
ENV NODE_ENV=production

# Expose the port that the MCP server will run on
EXPOSE 3000

# Command to run the server
ENTRYPOINT ["node", "build/index.js"]